### ISSUE TITLE
How to use <leader> in keymaps

### ISSUE THREAD

**Issue by nobleach** [andrewferrier/debugprint.nvim#111]
With the previous versions this plugin was using NeoVim's default keymaps with global functions. I realize this package now uses its own internal keymap functionality:
```lua
	opts = {
		keymaps = {
			normal = {
				plain_below = "g?p",
				plain_above = "g?P",
				variable_below = "g?v",
				variable_above = "g?V",
```
I've tried using `variable_below = "<leader>cl",` but it doesn't seem to work. Is there some other way?

**Comment by andrewferrier** [comment]
@nobleach thanks for spotting this. This was due to a recent change I made where I clumsily defaulted to lazy-loading by mistake. I've put in a temporary workaround for this, so if you pull the latest version, this should start working.

I'll work on a more permanent fix later.

**Comment by andrewferrier** [comment]
(Note to self: add tests for this also using lazy)

**Comment by nobleach** [comment]
The temporary workaround appears to work. Thank you for looking at it!

**Comment by andrewferrier** [comment]
Thanks, re-opening just because I want to fix it properly :)

**Comment by nobleach** [comment]
Understandable. Thanks again.
