### ISSUE TITLE
Improve by detecting the statement end position

### ISSUE THREAD

**Issue by GopherJ** [andrewferrier/debugprint.nvim#112]
debugprint now insert in next line, but one expression or statement may be across multiple lines like:

```rust
let a = b
   .set_x(1)
   .set_y(1);
```

in this case debug a will give wrong result

**Comment by andrewferrier** [comment]
@GopherJ I did consider this in issue #74, which I closed as being too complex to implement given all of the different languages `debugprint` supports - `debugprint` is meant to be a lightweight tool.

If someone was willing to invest the time to create an extensible language-by-language mechanism that supports doing something like this, maybe with support for a few of the popular languages (lua? python? typescript?) I'd certainly discuss adding it. But right now I don't think there's return on investment in adding it. Almost always inserting lines only where they are appropriate and/or moving them with syntactically incorrect is not difficult for an experienced developer.
