### ISSUE TITLE
`variable_above_alwaysprompt` not working

### ISSUE THREAD

**Issue by adriafarres** [andrewferrier/debugprint.nvim#115]
Hello! Thanks for writting debugprint! It's been very useful so far :-)

`variable_above_alwaysprompt` doesn't seem to do anything. I tried this on an empty neovim installation with the following config:

```lua
  opts = {
    keymaps = {
      normal = {
        variable_below_alwaysprompt = 'g?a',
        variable_above_alwaysprompt = 'g?A',
      }
    }
  },
```

**Comment by andrewferrier** [comment]
@adriafarres great, thanks for the feedback!

Thanks for raising this issue too. Unfortunately, I can't recreate it.

I tried with this `lazy.nvim` config:

```lua
return {
    "https://github.com/andrewferrier/debugprint.nvim/",
    opts = {
        keymaps = {
            normal = {
                variable_below_alwaysprompt = 'g?a',
                variable_above_alwaysprompt = 'g?A',
            }
        }
    },
}
```

This seems to work for me; if I open e.g. a Python file, put the cursor over a variable, and hit `g?a`, it prompts for a variable name in the command line, with the variable under the cursor pre-filled.

Can you be any more precise about what you mean when you say it "doesn't work"? Specifically:

1. What version of NeoVim and `debugprint`?
2. When you hit `g?a` or `g?A` what exactly happens?
3. What happens if you use one of the other default `debugprint.nvim` keys, like `g?p`?
4. What do you see if you type `:map g?a`?

Thanks,
Andrew.

**Comment by adriafarres** [comment]
Version:

```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1723675123
Run "nvim -V1 -v" for more info
```

Minimal config (based on what the author of oil.nvim does in his bug reports):

```lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "andrewferrier/debugprint.nvim",
    config = function()
      require("debugprint").setup({
        keymaps = {
          normal = {
            variable_below_alwaysprompt = 'g?a',
            variable_above_alwaysprompt = 'g?A',
          }
        }
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

If I run `nvim -u repro.lua main.py` with the following contents:

```python
some_var = 1
```

pressing `g?a` displays the `Variable name: some_var` popup and then appends the corresponding line, while pressing `g?A` displays the popup but doesn't prepend any line.

**Comment by andrewferrier** [comment]
Hah! Thanks for the detailed and easy way to recreate. I will have to adopt this approach for future bug reports.

In the meantime, I can see the issue now. Let me work on a fix...

**Comment by andrewferrier** [comment]
Hello - I believe this is fixed now on `main` - it's not yet in a release. Please re-test and see if it's fixed for you. This took a surprisingly long time to figure out, but in the end it was just some duplicate logic - copy and paste error!

Thanks for spotting it.

**Comment by adriafarres** [comment]
Works perfectly now. Thank you for fixing it :-)

**Comment by andrewferrier** [comment]
> Works perfectly now. Thank you for fixing it! :-)

Splendid, thanks for confirming!
