### ISSUE TITLE
Rust: debug log can be formatted by rustfmt into multiple lines

### ISSUE THREAD

**Issue by xixiaofinland** [andrewferrier/debugprint.nvim#119]
For example, if the line is beyond the max_width, rustfmt will auto-formatted it into multiple lines:

```
            eprintln!(
                "gopro[6]: rewrite.rs:213: try_add_standalone_suffix={:#?}",
                try_add_standalone_suffix
            );
```

then the command to delete debug lines will only delete one line.
```
            eprintln!(
                try_add_standalone_suffix
            );
```

**Comment by andrewferrier** [comment]
Thanks for the issue. Yes, I'm aware of this one. I don't have an easy "fix". Generally, I avoid formatting a file until the very end of my changes (i.e. when I've finished using debugprint and removed all the lines), but I'm aware that not everyone works this way. Maybe there is something clever I can do with extmarks or similar. I also don't want to over engineer either though; this is supposed to be a relatively basic tool. I'll mull this one over… Any suggestions welcome.

**Comment by xixiaofinland** [comment]
This issue is OK for me as either a fix or to be passed over. It's really not a big issue and is reported here in case people are unaware. @andrewferrier 

I haven't examined the debugprint code in detail. Naively, I believe 'debug' is also a normal AST node in tree-sitter. Would it be relatively straightforward to identify it by the node and keyword combination, rather than just a single line and keyword?

**Comment by andrewferrier** [comment]
Thanks for your feedback and input @xixiaofinland. Hopefully you understand why I chose not to implement this for now, I have documented this as a limitation. If someone is interested in doing the work and opening a pull request, I would certainly discuss it.

**Comment by xixiaofinland** [comment]
sure, totally understand.

I'm using it with Salesforce Apex language, and trying it out for different scenario fir a couple of weeks.
Once it's baked into my working flow and my setting is stable, i will make a PR for supporting Apex :)

Thanks again Andrew for this great tool!

**Comment by andrewferrier** [comment]
No problem, Apex support would be very welcome - feel free :)
