### ISSUE TITLE
Is it possible to make the log message stand out more?

### ISSUE THREAD

**Issue by mikavilpas** [andrewferrier/debugprint.nvim#132]
The plugin works great and I like it a lot. However, it's sometimes difficult to tell which messages are custom and which are from the actual application that I'm working with.

![image](https://github.com/user-attachments/assets/800fe0ac-fecc-4cd6-9f4b-7e5a1e821e95)

I was wondering if I could for example add emoji to the log message 🙂 My terminal (wezterm) is able to render emoji just fine and they stand out very well since they are colored (pictures).

For example (partial log message)

```text
🤔 DEBUGPRINT[16]: permanent-delete-test.ts:1106
```

**Comment by andrewferrier** [comment]
@mikavilpas I'm reluctant to do something that 'playful' by default, as some may not like and there are still terminals out there which don't render this well. It's easy to change this for yourself though, just use the `print_tag` configuration option and set it to `🤔 DEBUGPRINT` or whatever you like.

**Comment by mikavilpas** [comment]
Oh I must have missed it in the docs. That works well for me, thanks 🙂👍🏻

**Comment by andrewferrier** [comment]
> Oh I must have missed it in the docs. That works well for me, thanks 🙂👍🏻

No worries, thanks for the feedback and for all your contributions so far. Any other input or ideas very welcome.
