### ISSUE TITLE
Set display_location by filetype

### ISSUE THREAD

**Issue by ruicsh** [andrewferrier/debugprint.nvim#135]
Hi, great plugin. 

I'd like to set `display_location` by file type. For example, it may be quite useful to have location displayed for lua files, but not so much for typescript files if you're using the browser where all logs already have a file location displayed by the browser's console.

I'd suggest having `display_location` accept an optional function where we can leverage `vim.bo.filetype`. Or accept display_location on the `filetypes` tables.

**Comment by andrewferrier** [comment]
That makes sense, and I'm fact it might even make sense to extend this to the other display_* options. Hopefully a fairly straightforward change; I'll work on this. Thanks for the feedback.

**Comment by andrewferrier** [comment]
OK, I've had a think about the right way to implement this. What I think I'll do is that for now I will support `display_location`, `display_counter` and `display_snippet` at the filetype level, so they can be overriden on a per-filetype basis. I think that will alleviate your immediate need.

Then, to add flexibility, I will work longer-term on implementing #21, which will allow for a dynamic callback every time a debugprint line is inserted, optionally further overriding these values in addition to the `left`, `right`, etc. for the filetype. I think that allows for maximum flexibility.

**Comment by ruicsh** [comment]
that's great, cheers!

**Comment by andrewferrier** [comment]
Hi, I've implemented this now - I think this should do what you were after. Please test it out and let me know how it works for you.

**Comment by ruicsh** [comment]
works great, thanks a lot!

**Comment by andrewferrier** [comment]
> works great, thanks a lot!

Great, thanks for confirming!
