### ISSUE TITLE
feature request:  persistence the couter and can handly reset it.

### ISSUE THREAD

**Issue by soluty** [andrewferrier/debugprint.nvim#143]
Thanks for great plugin
currently  when  quit  nvim ,  the debugprint counter will  reset to 1,  it is not a best practice and will let some one lost there debug prints, because counter is the easyer way to find difference.  it will be nice if  we can persistence the couter and if need reset,  supply a command to reset it.

**Comment by andrewferrier** [comment]
This has been implemented on the main branch now (not in a stable release yet). Please try it out and see if you have any feedback.

**Comment by soluty** [comment]
Thank you, it works very well, i love this feature~~
