### ISSUE TITLE
Make dot-repeatable

### ISSUE THREAD

**Issue by andrewferrier** [andrewferrier/debugprint.nvim#3]
See https://github.com/kylechui/nvim-surround/blob/7b8a295a27038715bc87c01277d82c294b690e6d/lua/nvim-surround/cache.lua#L12

**Comment by kylechui** [comment]
If you have any questions about the "flow" of how dot-repeating works, feel free to tag me. I probably plan on writing a gist at some point in the future that describes how `nvim-surround` handles it.

**Comment by andrewferrier** [comment]
Funny you should say... I was wondering :) Haven't quite got around to figuring it out yet. I'll take a look at your code and see if I can work it backwards. But a gist/blog article/whatever would make a lot of sense... not sure this is well described in the NeoVim/lua world.

**Comment by andrewferrier** [comment]
Oh, and I'm not sure if it's a plugin that interests you... but any feedback on debugprint.nvim very welcome :) I've got a few more issues to close before my first proper announce on reddit :)

**Comment by kylechui** [comment]
I might not use it personally, but I can definitely see the value in it; I've personally just been using [my print surround](https://github.com/kylechui/nvim-surround/discussions/53#discussioncomment-3341113) for debugging, as I tend to only have one or two print statements at a time.

**Comment by kylechui** [comment]
I'm not great at writing (also I'm not entirely sure what parts of dot-repeating are the most confusing), but here's a [preliminary draft of how to set up dot-repeat yourself](https://gist.github.com/kylechui/a5c1258cd2d86755f97b10fc921315c3).

**Comment by andrewferrier** [comment]
> I'm not great at writing (also I'm not entirely sure what parts of dot-repeating are the most confusing), but here's a [preliminary draft of how to set up dot-repeat yourself](https://gist.github.com/kylechui/a5c1258cd2d86755f97b10fc921315c3).

This is great :) Your writing skills seem pretty good to me, and this is a really clear explanation. Worth publicising etc. on reddit in standalone form I would say. At least request to add it to https://github.com/nanotee/nvim-lua-guide, as I think this will be very helpful for plugin authors.

**Comment by kylechui** [comment]
I made [a short Reddit post](https://www.reddit.com/r/neovim/comments/wkqkzf/adding_dotrepeat_to_plugins/) here; I might consider adding it to the Neovim Lua guide once it feels... more polished. In any case, glad I was able to help you with this :)

**Comment by andrewferrier** [comment]
> I made [a short Reddit post](https://www.reddit.com/r/neovim/comments/wkqkzf/adding_dotrepeat_to_plugins/) here; I might consider adding it to the Neovim Lua guide once it feels... more polished. In any case, glad I was able to help you with this :)

No worries, and thanks again for the help! Really saved me a lot of time...

**Comment by andrewferrier** [comment]
@kylechui FYI I announced/released debugprint.nvim: https://www.reddit.com/r/neovim/comments/wlwofb/announcing_debugprintnvim_debug_via_print/. Just in case you're interested :) Thanks again for helping me figure out the dot-repeat.
