### ISSUE TITLE
Setup config seems to not work

### ISSUE THREAD

**Issue by thekaganugur** [andrewferrier/debugprint.nvim#46]
Hi,

I wanted to customize `DEBUGPRINT` with the following code snippet:
```
require("debugprint").setup({
	print_tag = "DEBUG",
})
```

But this doesn't change `DEBUGPRINT` to `DEBUG`.

**Comment by thekaganugur** [comment]
I tried `display_counter = false` and it works, so I've changed to title.

**Comment by andrewferrier** [comment]
So I can't recreate this problem... I just tried it and for me this does change the print tag. 

Are you sure you are only calling `setup()` once? If you called it again you would reset the options.

**Comment by thekaganugur** [comment]
Yes, my bad. Turns out it was because of

```
    use({
        "andrewferrier/debugprint.nvim",
        config = function()
            require("debugprint").setup()
        end,
    })

```

even though I deleted the setup from here it kept executing. 
Thanks

**Comment by andrewferrier** [comment]
No problem, glad to know it's working!
