### ISSUE TITLE
Generate the debug print such that the content is printed on stderr instead of stdout

### ISSUE THREAD

**Issue by ardubev16** [andrewferrier/debugprint.nvim#48]
Currently the default configuration prints debugs on stdout, it would be nicer if it would print them on stderr (since these are debug prints) where possible or, at least, make an option to decide between the two.

**Comment by andrewferrier** [comment]
@ardubev16 I think this is a great idea! Ultimately this should probably apply to all filetypes, but did you have any in particular you were thinking of?

I might not be able to get to this for a few weeks, if you'd like to submit any pull requests in the meantime, I'll gladly accept them as long.

Thanks.

**Comment by andrewferrier** [comment]
As a result of #49, some filetypes now print on stderr instead. By my assessment, `dart`, `docker`, `javascript`, `lua`, `make` and `vim` still do not. I will keep this issue open to track that need as they (especially lua) need more extensive unit tests changes and I may not have time right away. PRs welcome if anyone wants to work on them, as long as they include the relevant test changes.
