### ISSUE TITLE
Add newline character for c

### ISSUE THREAD

**Issue by m0n0pr1x** [andrewferrier/debugprint.nvim#50]
Is it possible to add new line character for debug print in C ?
    fprintf(stderr, "DEBUGPRINT[1]: .....: keys=%d", keys);
become
    fprintf(stderr, "DEBUGPRINT[1]: ....: keys=%d\n", keys);

**Comment by andrewferrier** [comment]
Thank you for spotting this, this was a mistake. Fixed now I think - let me know if you see any issues.
