### ISSUE TITLE
The rust debug print maybe should use `{:#?}`

### ISSUE THREAD

**Issue by IndianBoy42** [andrewferrier/debugprint.nvim#52]
IE debug not display and 'pretty'/expanded print

**Comment by andrewferrier** [comment]
Hi, thanks for the idea, sounds positive - but I don't really write much rust. Can you expand a little on what you're suggesting? What do you mean by "debug not display"?

**Comment by andrewferrier** [comment]
Are you suggested that this line (https://github.com/andrewferrier/debugprint.nvim/blob/425131e8c105ffdc6ca49440814749c65033d6e8/lua/debugprint/filetypes.lua#L95) should change to `mid_var = '{:#?}", '`?

So the overall output would look like:

`eprintln!("DEBUGPRINT[1]: x.rs:1: thing={:#?}", thing);`

Does that look right?

**Comment by IndianBoy42** [comment]
Yes, so basically rust has 2 traits for stringifying objects: Display and Debug. Display is more for user-facing representations while Debug is generally for developers and debugging, as the name suggests. Debug implementations are a lot more common because they can be automatically generated. `{:?}` uses the Debug representation, and adding `#` spreads out the printing onto many lines with nicer indentation and everything, so while its more verbose it's usually preferred for debugging. 

That change you mentioned sounds correct, I can probably try it out and submit a PR in a couple of days

**Comment by andrewferrier** [comment]
No, that's fine, it's a quick change, I can and will do  it right now.

**Comment by andrewferrier** [comment]
OK, I've done this, please update and test to check if this is OK for you. Thanks!
