### ISSUE TITLE
Support treesitter variable names in Typescript

### ISSUE THREAD

**Issue by andrewferrier** [andrewferrier/debugprint.nvim#60]
See https://github.com/andrewferrier/debugprint.nvim/issues/59 for the background.

**Comment by andrewferrier** [comment]
So I've just been looking at the code snippet originally provided in #59...

```typescript
export async function loader({ context, request }: LoaderArgs) {
  //-------------------------------^  This is a variable
  const config = ConfigProvider.getInstance('development').getConfig();
}
```

Interestingly, in this context, the Treesitter tree shows context as a `(shorthand_property_identifier_pattern)`. I don't know exactly what that means and whether that's reliably always a variable but I need to do some more experimentation.

**Comment by andrewferrier** [comment]
@nobleach this was easier than expected, I think this specific case should work automatically now...

**Comment by nobleach** [comment]
Looks perfect! Thanks again!
