### ISSUE TITLE
See if there's a way to detect accidental 'expr' in mapping and warn

### ISSUE THREAD

**Issue by pavkam** [andrewferrier/debugprint.nvim#66]
Not sure why this is happening. Disabled all plugins one by one and my auto-commands and keybindings, lsp, formatted and lining. Still happens

```
E5108: Error executing lua: .../share/nvim/lazy/debugprint.nvim/lua/debugprint/init.lua:313: Failed to save undo information
stack traceback:
	[C]: in function 'nvim_buf_set_lines'
	.../share/nvim/lazy/debugprint.nvim/lua/debugprint/init.lua:313: in function <.../share/nvim/lazy/debugprint.nvim/lua/debugprint/init.lua:284>
```
`Neovim 0.9.4`

![image](https://github.com/andrewferrier/debugprint.nvim/assets/7327309/23aea609-2c19-4c9d-9041-d3455958ecb1)

**Comment by andrewferrier** [comment]
@pavkam I haven't seen this, although it sounds like it might a textlock issue.

It would be good to be able to recreate this. How precisely are you triggering the removal of debug prints? Are you using the default `:DeleteDebugPrints` command?

Note to self:

* https://github.com/neovim/neovim/issues/21055

**Comment by pavkam** [comment]
Hi @andrewferrier, sorry for late reply,

My keybinding is this:
```
{
            '<leader>Dd',
            function()
                -- TODO this fails with error
                return require('debugprint').deleteprints()
            end,
            mode = { 'n' },
            expr = true,
            desc = 'Remove all debug prints in buffer',
        },
```

**Comment by pavkam** [comment]
This makes sense since I mistakenly used' expr' (copy-paste). I've removed the expr and `return` and it started working fine.

Sorry about that, did not notice :(

**Comment by andrewferrier** [comment]
@pavkam no problem, glad you got it working. I'm going to keep this issue open to see if there's a way in future I can detect and warn on that.

Thanks for updating me and for feeding back on the plugin!

**Comment by andrewferrier** [comment]
OK, having looked into this, I don't think there's any reasonable way to detect this. I think I'm going to close this issue in favour of #44 ; once that's resolved, I'll provide a better way to set up custom keybindings / commands anyway.
