### ISSUE TITLE
Consider changing console.debug to console.log

### ISSUE THREAD

**Issue by andrewferrier** [andrewferrier/debugprint.nvim#72]
https://www.reddit.com/r/neovim/comments/1848aoc/comment/kaw948m/?utm_source=share&utm_medium=web2x&context=3

**Comment by andrewferrier** [comment]
This has been done: https://github.com/andrewferrier/debugprint.nvim/commit/c8341fddca633ffe8b50474601c3651f260dbeed.

**Comment by CarlosMed** [comment]
I know you had set this to `console.warn` but this sometimes muddies the console as seen In the pic. If you default to `console.log`, it should suffice for everything under the JS umbrella. 

<img width="1367" alt="image" src="https://github.com/andrewferrier/debugprint.nvim/assets/7547059/434dfc20-34b5-4329-be1d-49ed61017ae9">

**Comment by andrewferrier** [comment]
@CarlosMed hmm, this is a tricky one. JavaScript is not just used in browsers, but in NodeJS and other runtimes too, so I'm cautious about optimising for the browser use case by creating an exception from the usual principle of making DEBUGPRINT stand out, common though it might be. Is that the *default* behaviour of your browser?

**Comment by andrewferrier** [comment]
@CarlosMed so I've done some testing of `console.log()`, `console.warn()`, `console.debug()` and `console.error()`:

* On NodeJS, they all display the same by default, except that `warn` and `error` go to stderr (which I consider desirable, albeit not essential, following the principles [here](https://github.com/andrewferrier/debugprint.nvim/blob/0c81cd2bab372bba99815f505eb1fe759d38dd88/lua/debugprint/filetypes.lua#L1).

* On Firefox (Librewolf 121.0 to be precise), it displays `log` and `debug` in plain text, with `warn` in yellow text, and `error` in red text. None of the logging lines are 'expanded' in the way you show.

* On Chrome (121), it displays 'log', 'warn', and 'error' by default, with warn in yellow and error in red by default. Again, all of the logging lines are just single lines and not 'expanded'.

I can't recreate what you are showing in your screenshots. My guess would be (I don't do much browser JavaScript) that you are logging an variable/object with a stacktrace called 'error', in which case it makes sense (I think) that it's expanded.

So I'm unclear what issue you're referring to when you say 'way too much info' - from my testing it seems like it's the same level of info whichever console method you use. Can you provide some more specific recreation instructions?

Of course, remember you can always override the behaviour in any event in your own config as described [here](https://github.com/andrewferrier/debugprint.nvim#add-custom-filetypes). If you specify an existing filetype, it will override the behaviour for that filetype.

**Comment by CarlosMed** [comment]
The above solved my issue. Since it makes it flexible. Thank you!

**Comment by andrewferrier** [comment]
OK, thanks. I'm closing this issue since I can't recreate the specific problem you described and it sounds like you've fixed with changes to your own config. Thanks for your contribution!

**Comment by tolluset** [comment]
For those who followed by `console.warn` issuse, if you use javascript and typescript (and react) maybe you should set whole languages like below.

I'm changed `console.warn` -> `console.info` by this setting. (in lazyvim)

```lua
 return {
  {
    "andrewferrier/debugprint.nvim",
    config = function()
      require("debugprint").setup({
        filetypes = {
          ["js"] = {
            left = 'console.info("',
            right = '")',
            mid_var = '", ',
            right_var = ")",
          },

          ["javascript"] = {
            left = 'console.info("',
            right = '")',
            mid_var = '", ',
            right_var = ")",
          },

          ["javascriptreact"] = {
            left = 'console.info("',
            right = '")',
            mid_var = '", ',
            right_var = ")",
          },

          ["typescript"] = {
            left = 'console.info("',
            right = '")',
            mid_var = '", ',
            right_var = ")",
          },

          ["typescriptreact"] = {
            left = 'console.info("',
            right = '")',
            mid_var = '", ',
            right_var = ")",
          },
        },
      })
    end,
    version = "*",
  },
}
```

**Comment by andrewferrier** [comment]
Thanks @tolluset! I'll keep the default will stay at `console.warn()` for now, given [the investigation above](https://github.com/andrewferrier/debugprint.nvim/issues/72#issuecomment-1902469694), unless someone can give a compelling reason otherwise, but I am considering creating a semi-official 'showcase' of alternative `debugprint` setups, and I might adapt something like this into that showcase. Thanks for the heads-up.

By the way, you can do this a bit more efficiently like this:


> ```lua
>  local js_like = {
>    left = 'console.info("',
>    right = '")',
>    mid_var = '", ',
>    right_var = ")",
>  }
>
>  return {
>   {
>     "andrewferrier/debugprint.nvim",
>     config = function()
>       require("debugprint").setup({
>         filetypes = {
>           ["javascript"] = js_like,
>           ["javascriptreact"] = js_like,
>           ["typescript"] = js_like,
>           ["typescriptreact"] = js_like,
>         },
>       })
>     end,
>     version = "*",
>   },
> }
> ```

**Comment by andrewferrier** [comment]
Oh, and just a heads-up @tolluset - `js` isn't a valid filetype in NeoVim, I believe - it's `javascript`.

**Comment by tolluset** [comment]
> Thanks @tolluset! I'll keep the default will stay at `console.warn()` for now, given [the investigation above](https://github.com/andrewferrier/debugprint.nvim/issues/72#issuecomment-1902469694), unless someone can give a compelling reason otherwise, but I am considering creating a semi-official 'showcase' of alternative `debugprint` setups, and I might adapt something like this into that showcase. Thanks for the heads-up.
> 
> By the way, you can do this a bit more efficiently like this:
> 
> > ```lua
> >  local js_like = {
> >    left = 'console.info("',
> >    right = '")',
> >    mid_var = '", ',
> >    right_var = ")",
> >  }
> > 
> >  return {
> >   {
> >     "andrewferrier/debugprint.nvim",
> >     config = function()
> >       require("debugprint").setup({
> >         filetypes = {
> >           ["javascript"] = js_like,
> >           ["javascriptreact"] = js_like,
> >           ["typescript"] = js_like,
> >           ["typescriptreact"] = js_like,
> >         },
> >       })
> >     end,
> >     version = "*",
> >   },
> > }
> > ```


This way looks great!! Thanks!!! ☺️

**Comment by andrewferrier** [comment]
> This way looks great!! Thanks!!! ☺️

FYI - I'm now starting to track configurations such as this in a [showcase](https://github.com/andrewferrier/debugprint.nvim/blob/main/SHOWCASE.md).
