### ISSUE TITLE
Make debugprint.nvim only put statements in places where they are syntactically correct

### ISSUE THREAD

**Issue by roginfarrer** [andrewferrier/debugprint.nvim#74]
Hey there, thanks for the neat plugin. I just started playing with it, and was surprised that the plugin will place debug statements in the middle of a multi-line variable declaration. I think with Treesitter, we could probably find the end of the variable declaration?

Here's an example in JS:

```js
const payload = foo({   // <- I hit g?p
						// <- debugprint puts the console.log here, breaking the file
  a: 'b',
  c: 'd',
});
						// <- I expect the console.log here, after the declaration
```

**Comment by andrewferrier** [comment]
@roginfarrer thanks. I think you're right that in theory Treesitter contains enough info to figure this out, although I don't know how easy it is in the general case across all languages that debugprint supports. For now I was working on the KISS principle and not trying to over engineer this, but I'll certainly look into it. May not be a quick fix though :)

Thanks for your input and comments!

**Comment by andrewferrier** [comment]
The more I've thought about this, I think unfortunately this is just impractical for `debugprint` - even using treesitter, it would have understand the syntactic nuances of each language it supports to understand where a statement can and cannot be put. This goes far beyond the current investment to support a new filetype for `debugprint` as I don't think this information is easily available out of the box.

If someone is willing to suggest a sensible approach that won't be too much of a headache to maintain, I'm willing to consider it, but for now, I'm going to close this as practically unimplementable.
