### ISSUE TITLE
debugprint command doesn't work in python

### ISSUE THREAD

**Issue by Mte90** [andrewferrier/debugprint.nvim#75]
I have:

```
vim.keymap.set("n", "<Leader>p", function()
    require('debugprint').debugprint( { above = true, variable = true } )
end)
```

Asks for the variable name but after pressing enter nothing happens and the debugprint is not added.

**Comment by andrewferrier** [comment]
@Mte90 this does work, but you have to make sure you returning the value of the `debugprint()` invocation, and declaring the keymap using `expr = true`. See examples here: https://github.com/andrewferrier/debugprint.nvim#custom-keymappings-and-commands. I don't know of a better way to handle this right now, except maybe to provide a first-class way to override keymaps in the plugin config (see #44) - any feedback on this welcome.

**Comment by Mte90** [comment]
You are right, in that way works.
Probably something that let's from the plugin setup to set the bindings will fix that issue and also simplify the mapping managements in the user configuration.

**Comment by andrewferrier** [comment]
Agreed @Mte90 I'll work on that in issue #44. Thanks for the feedback, glad you fixed it!
