### ISSUE TITLE
Adding a FOSS license

### ISSUE THREAD

**Issue by ColinKennedy** [andrewferrier/debugprint.nvim#76]
Hi, I love and use this plug-in every day for Python and Lua. It's one of those "small but used dozens of times" plug-ins that everyone should use! My workplace is cautious about allowing code without a `LICENSE` file and it'd be a big help if this plug-in could use a FOSS license. I'm sure others in the same position and would appreciate it too. Could a FOSS license please be added if this plug-in is meant for public use?

**Comment by andrewferrier** [comment]
Hi Colin, thanks very much for your feedback, it's really appreciated! It's nice
that you find `debugprint.nvim` useful. I was very surprised on checking to
discover that you're correct, I don't have a LICENSE! This was a total oversight
and certainly not how I meant things to be. I've now added an MIT license so
hopefully that meets with your needs.

**Comment by ColinKennedy** [comment]
That's great to hear and thank you for your quick reply!

**Comment by ColinKennedy** [comment]
One small thing if you don't mind - I prefer releases so I'm on v1.6.0. If the license could be added to that release, I'd be grateful. Or I can use the default branch. Either is okay for me. Thank you again!

**Comment by andrewferrier** [comment]
You're right again, it justifies a new release. v1.7.0 now available :)
