### ISSUE TITLE
JavaScript in HTML will prompt [Don't have debugprint configuration for filetype html]

### ISSUE THREAD

**Issue by DevilSquirrel** [andrewferrier/debugprint.nvim#84]
Can it still work in the JavaScript code of the HTML file

**Comment by andrewferrier** [comment]
Hi - in general this should already work, but there were a few corner cases where it wasn't triggering on quite the right line/column. I've just fixed those I think - please update and verify if this works for you.

If you're still having issues, please provide a sample file you're trying to add debugprinting to so I can recreate the problem.

Thanks for raising this!

**Comment by DevilSquirrel** [comment]
Thank you

> Hi - in general this should already work, but there were a few corner cases where it wasn't triggering on quite the right line/column. I've just fixed those I think - please update and verify if this works for you.
> 
> If you're still having issues, please provide a sample file you're trying to add debugprinting to so I can recreate the problem.
> 
> Thanks for raising this!

Thank you  ！
Everything is normal now
