### ISSUE TITLE
Add a toggle function to comment all debugprint

### ISSUE THREAD

**Issue by xzbdmw** [andrewferrier/debugprint.nvim#85]
I think it's useful to temporarily comment out these print statements because if it's just deletion, then if you want to see the print again, you'll have to regenerate it

**Comment by andrewferrier** [comment]
@xzbdmw interesting idea, and - famous last words - I don't think too hard to implement. I'll take a look at it. Thanks!

**Comment by andrewferrier** [comment]
@xzbdmw hi, this has been implemented now, please try out the latest version of NeoVim on the `main` branch. There is a command added by default called `ToggleCommentDebugPrints` which should do what you want.

You will need to have `mini.nvim` installed also (even if you don't use it) - the README shows how to make this a dependency.

**Comment by andrewferrier** [comment]
Note that - hot off the press - `mini.nvim` is now no longer needed on NeoVim 0.10+ (nightly) since it supports comments inbuilt. Still needed for older NeoVim versions.
