### ISSUE TITLE
Make treesitter queries language-specific and adjust variable_name query for PHP

### ISSUE THREAD

**Issue by RayGuo-ergou** [andrewferrier/debugprint.nvim#89]
### Issue
The php default fileformat would show variable value twice and no variable name. Here's an example ( also a screenshot with treesitter highlight attached for better visibility)

```php
$branchCode = 'au';
fwrite(STDERR, "DEBUGPRINT[1]: test.php:7: $branchCode=$$branchCode\n");
```

Which will output in:

```bash
DEBUGPRINT[1]: test.php:7: au=$au
```

![image](https://github.com/andrewferrier/debugprint.nvim/assets/33137074/202caf86-4154-48fd-8064-1e040ebde256)

### proposal result 

I tried to use the template below which will output: `DEBUGPRINT[1]: test.php:7: $branchCode=au%`

*I saw in the readme that issue is preferred so I decide not to create a PR.*
```lua
["php"] = {
    left = "fwrite(STDERR, '",
    right = "\\n');",
    mid_var = "' . ",
    right_var = ");",
},
```

Will output:
```php
fwrite(STDERR, 'DEBUGPRINT[1]: test.php:7: $branchCode=' . $branchCode);
```

### Note
I did change the double quote to single quote as I did not find a way to output the following:
```php
fwrite(STDERR, "DEBUGPRINT[1]: test.php:7: \$branchCode=$branchCode\n");
                                        // ^ No idea how to add the back slash here.
```

**Comment by RayGuo-ergou** [comment]
I just realized this will break `g?p`. 🤔

**Comment by andrewferrier** [comment]
@RayGuo-ergou thanks for bringing this to my attention! I don't work with PHP much and hadn't noticed. I'll fix this.

**Comment by RayGuo-ergou** [comment]
My cursor was on `$`, and if my cursor is on `branchCode` then hit `g?v`, neovim takes me to command mode, see image below.
![image](https://github.com/andrewferrier/debugprint.nvim/assets/33137074/d76962cf-6a2e-440a-93d3-c31bf4945d2e)

Maybe because neovim's version?

here's my version
```
NVIM v0.10.0-dev-2745+g5a5d26b4a
Build type: RelWithDebInfo
LuaJIT 2.1.1710088188
Compilation: /usr/bin/cc -O2 -g -Og -g -flto -fno-fat-lto-objects -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fstack-protector-strong -Wno-conversion -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto  -DUNIT_TESTING -DHAVE_UNIBILIUM -D_GNU_SOURCE -DINCLUDE_GENERATED_DECLARATIONS -I/home/raydev/git/neovim/.deps/usr/include/luajit-2.1 -I/home/raydev/git/neovim/.deps/usr/include -I/home/raydev/git/neovim/build/src/nvim/auto -I/home/raydev/git/neovim/build/include -I/home/raydev/git/neovim/build/cmake.config -I/home/raydev/git/neovim/src -I/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by RayGuo-ergou** [comment]
Might related to `treesitter`, tried to set `ignore_treesitter = true`, then the cursor sitting on both `$` and `branchCode` takes me to the command mode.

**Comment by RayGuo-ergou** [comment]
![GIF 4-1-2024 12-35-51 AM](https://github.com/andrewferrier/debugprint.nvim/assets/33137074/284cc8f8-980e-40f5-a723-f378d8c07160)

I have record a gif, hope this makes sense.

**Comment by RayGuo-ergou** [comment]
![image](https://github.com/andrewferrier/debugprint.nvim/assets/33137074/0bd9a29e-a9ea-48e7-bc2e-f7befeb45631)
![image](https://github.com/andrewferrier/debugprint.nvim/assets/33137074/e3b00536-a8b7-4263-84ea-038f70660e78)

Tree sitter does not recognize the variable without `$` I think this is the root cause.

**Comment by RayGuo-ergou** [comment]
Sorry for spamming messages but I believe this is the root cause:

https://github.com/andrewferrier/debugprint.nvim/blob/76a7c785598ac3a9f81cdc83e9b4a03c00a8b510/lua/debugprint/utils.lua#L145

![image](https://github.com/andrewferrier/debugprint.nvim/assets/33137074/f5ff56ee-6471-4378-a1de-867742e582d3)

**Comment by andrewferrier** [comment]
@RayGuo-ergou aha, I understand now, and yes I can recreate the same behavior. In PHP the `$` is not really part of the variable name but the logic here is too simplistic, I'm looking for `variable_name` for another language, the Treesitter checks really need to be language-specific.

I'll work on that, but in the meantime you can work around this by moving one char to the right before you hit `g?v`.

**Comment by andrewferrier** [comment]
Thanks for your hard work in tracking it down more specifically by the way :)

**Comment by RayGuo-ergou** [comment]
Thank you!

**Comment by andrewferrier** [comment]
Could be helpful: https://www.youtube.com/watch?v=86sgKa0jeO4

**Comment by andrewferrier** [comment]
FYI, this issue has now been resolved permanently with some of the recent internal changes I've made to `debugprint` to pick up Treesitter variables more accurately. I've also introduced a test specifically for this case to avoid it reoccurring.

Thanks again for your input on this issue.

**Comment by RayGuo-ergou** [comment]
Thank you so much!
